mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
logging:
  level:
    org.thymeleaf: info
#    org.springframework.web: debug
#    org.springframework.boot.test: debug

